language: node_js
node_js:
  - 14.15.4

cache:
  directories:
    - node_modules

script:
  - yarn test

before_deploy:
  - npm install netlify-cli -g
  - yarn build

deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=build --prod
  on:
    branch: deploy